spring:
  sql:
    init:
      platform: h2
      mode: always
  datasource:
    url: jdbc:h2:mem:db-users
    username: ae
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 9000

application:
    jwt:
      secretKey: "securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure"
      tokenPrefix: Bearer
      tokenExpirationAfterHours: 1
      refreshTokenExpirationAfterHour: 12
